#DataBase configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_app
    username: postgres
    password: yassine
#Hibernate configuration
jpa:
  hibernate:
    ddl-auto: none
    show-sql: true

#token key
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
