spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_app
    username: postgres
    password: yassine
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmed.yassin.elhamzaoui2019@gmail.com
    password: hswxtybmtwpxjriv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#token key
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
